//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenCatch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotifications {
            get {
                return ((bool)(this["ShowNotifications"]));
            }
            set {
                this["ShowNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int CursorAreaW {
            get {
                return ((int)(this["CursorAreaW"]));
            }
            set {
                this["CursorAreaW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int CursorAreaH {
            get {
                return ((int)(this["CursorAreaH"]));
            }
            set {
                this["CursorAreaH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Action_PrtSc {
            get {
                return ((int)(this["Action_PrtSc"]));
            }
            set {
                this["Action_PrtSc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Action_Alt_PrtSc {
            get {
                return ((int)(this["Action_Alt_PrtSc"]));
            }
            set {
                this["Action_Alt_PrtSc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Action_Shift_PrtSc {
            get {
                return ((int)(this["Action_Shift_PrtSc"]));
            }
            set {
                this["Action_Shift_PrtSc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Action_Alt_Shift_PrtSc {
            get {
                return ((int)(this["Action_Alt_Shift_PrtSc"]));
            }
            set {
                this["Action_Alt_Shift_PrtSc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenEditor_PrtSc {
            get {
                return ((bool)(this["OpenEditor_PrtSc"]));
            }
            set {
                this["OpenEditor_PrtSc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenEditor_Alt_PrtSc {
            get {
                return ((bool)(this["OpenEditor_Alt_PrtSc"]));
            }
            set {
                this["OpenEditor_Alt_PrtSc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenEditor_Shift_PrtSc {
            get {
                return ((bool)(this["OpenEditor_Shift_PrtSc"]));
            }
            set {
                this["OpenEditor_Shift_PrtSc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenEditor_Alt_Shift_PrtSc {
            get {
                return ((bool)(this["OpenEditor_Alt_Shift_PrtSc"]));
            }
            set {
                this["OpenEditor_Alt_Shift_PrtSc"] = value;
            }
        }
    }
}
